MyModule needs to be capitalized.
Otherwise elixir thinks it is a function name and throws the following
error: "** (UndefinedFunctionError) undefined function:
IEx.Helpers.mymodule/0"